# Generated by Django 5.0.4 on 2024-05-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_total',
        ),
    ]
